from __future__ import annotations

from platform_core.providers.contracts import (
    AdsCampaignRecord,
    AdsLeadRecord,
    AdsMetricsRecord,
    AdsProvider,
    BankAccountRecord,
    BankBalanceRecord,
    BankProvider,
    BankTransactionRecord,
    ERPProvider,
    ERPProductRecord,
    ERPPurchaseRecord,
    ERPStockMovementRecord,
    ERPStockRecord,
    InboundMessageRecord,
    MessageSendRequest,
    MessageSendResult,
    MessagingProvider,
    ProviderRegistry,
    SpreadsheetProvider,
    SyncCursor,
)

__all__ = [
    "AdsCampaignRecord",
    "AdsLeadRecord",
    "AdsMetricsRecord",
    "AdsProvider",
    "BankAccountRecord",
    "BankBalanceRecord",
    "BankProvider",
    "BankTransactionRecord",
    "ERPProvider",
    "ERPProductRecord",
    "ERPPurchaseRecord",
    "ERPStockMovementRecord",
    "ERPStockRecord",
    "InboundMessageRecord",
    "MessageSendRequest",
    "MessageSendResult",
    "MessagingProvider",
    "ProviderRegistry",
    "SpreadsheetProvider",
    "SyncCursor",
]
