"""automation foundation

Revision ID: 2a718c2f124b
Revises: 7763ddc6df3e
Create Date: 2026-04-18 12:50:53.319707

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '2a718c2f124b'
down_revision = '7763ddc6df3e'
branch_labels = None
depends_on = None


def _uses_sqlite_batch() -> bool:
    return op.get_context().dialect.name == "sqlite"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active_version_number', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_rules_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules')),
    sa.UniqueConstraint('account_id', 'code', name=op.f('uq_rules_account_id'))
    )
    op.create_index(op.f('ix_rules_account_id'), 'rules', ['account_id'], unique=False)
    op.create_index('ix_rules_account_rule_type_status', 'rules', ['account_id', 'rule_type', 'status'], unique=False)
    op.create_index('ix_rules_account_status', 'rules', ['account_id', 'status'], unique=False)
    op.create_table('rule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_rule_versions_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_rule_versions_rule_id_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_versions')),
    sa.UniqueConstraint('rule_id', 'version_number', name=op.f('uq_rule_versions_rule_id'))
    )
    op.create_index('ix_rule_versions_rule_status', 'rule_versions', ['rule_id', 'status'], unique=False)
    op.create_table('threshold_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('threshold_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('value_numeric', sa.String(length=64), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_threshold_configs_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_threshold_configs_rule_id_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threshold_configs')),
    sa.UniqueConstraint('account_id', 'rule_id', 'threshold_key', name=op.f('uq_threshold_configs_account_id'))
    )
    op.create_index(op.f('ix_threshold_configs_account_id'), 'threshold_configs', ['account_id'], unique=False)
    op.create_index('ix_threshold_configs_account_rule_status', 'threshold_configs', ['account_id', 'rule_id', 'status'], unique=False)
    op.create_table('rule_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_version_id', sa.Integer(), nullable=False),
    sa.Column('execution_key', sa.String(length=191), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('evaluated_entity_type', sa.String(length=64), nullable=False),
    sa.Column('evaluated_entity_id', sa.String(length=64), nullable=False),
    sa.Column('window_key', sa.String(length=64), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('first_triggered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_rule_executions_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_rule_executions_alert_id_alerts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_rule_executions_recommendation_id_recommendations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_rule_executions_rule_id_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], name=op.f('fk_rule_executions_rule_version_id_rule_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_rule_executions_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_executions')),
    sa.UniqueConstraint('account_id', 'execution_key', name=op.f('uq_rule_executions_account_id'))
    )
    op.create_index('ix_rule_executions_account_entity_status', 'rule_executions', ['account_id', 'evaluated_entity_type', 'status'], unique=False)
    op.create_index(op.f('ix_rule_executions_account_id'), 'rule_executions', ['account_id'], unique=False)
    op.create_index('ix_rule_executions_account_rule_status', 'rule_executions', ['account_id', 'rule_id', 'status'], unique=False)
    if _uses_sqlite_batch():
        with op.batch_alter_table('alerts', recreate='always') as batch_op:
            batch_op.add_column(sa.Column('source_rule_id', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('dedupe_key', sa.String(length=191), nullable=True))
            batch_op.create_unique_constraint(op.f('uq_alerts_account_id'), ['account_id', 'dedupe_key'])
            batch_op.create_foreign_key(op.f('fk_alerts_source_rule_id_rules'), 'rules', ['source_rule_id'], ['id'], ondelete='SET NULL')
        with op.batch_alter_table('recommendations', recreate='always') as batch_op:
            batch_op.add_column(sa.Column('source_rule_id', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('dedupe_key', sa.String(length=191), nullable=True))
            batch_op.create_unique_constraint(op.f('uq_recommendations_account_id'), ['account_id', 'dedupe_key'])
            batch_op.create_foreign_key(op.f('fk_recommendations_source_rule_id_rules'), 'rules', ['source_rule_id'], ['id'], ondelete='SET NULL')
        with op.batch_alter_table('tasks', recreate='always') as batch_op:
            batch_op.add_column(sa.Column('source_rule_id', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('dedupe_key', sa.String(length=191), nullable=True))
            batch_op.add_column(sa.Column('escalation_level', sa.Integer(), nullable=False, server_default='0'))
            batch_op.add_column(sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))
            batch_op.create_unique_constraint(op.f('uq_tasks_account_id'), ['account_id', 'dedupe_key'])
            batch_op.create_foreign_key(op.f('fk_tasks_source_rule_id_rules'), 'rules', ['source_rule_id'], ['id'], ondelete='SET NULL')
    else:
        op.add_column('alerts', sa.Column('source_rule_id', sa.Integer(), nullable=True))
        op.add_column('alerts', sa.Column('dedupe_key', sa.String(length=191), nullable=True))
        op.create_unique_constraint(op.f('uq_alerts_account_id'), 'alerts', ['account_id', 'dedupe_key'])
        op.create_foreign_key(
            op.f('fk_alerts_source_rule_id_rules'),
            'alerts',
            'rules',
            ['source_rule_id'],
            ['id'],
            ondelete='SET NULL',
        )
        op.add_column('recommendations', sa.Column('source_rule_id', sa.Integer(), nullable=True))
        op.add_column('recommendations', sa.Column('dedupe_key', sa.String(length=191), nullable=True))
        op.create_unique_constraint(op.f('uq_recommendations_account_id'), 'recommendations', ['account_id', 'dedupe_key'])
        op.create_foreign_key(
            op.f('fk_recommendations_source_rule_id_rules'),
            'recommendations',
            'rules',
            ['source_rule_id'],
            ['id'],
            ondelete='SET NULL',
        )
        op.add_column('tasks', sa.Column('source_rule_id', sa.Integer(), nullable=True))
        op.add_column('tasks', sa.Column('dedupe_key', sa.String(length=191), nullable=True))
        op.add_column('tasks', sa.Column('escalation_level', sa.Integer(), nullable=False, server_default='0'))
        op.add_column('tasks', sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))
        op.create_unique_constraint(op.f('uq_tasks_account_id'), 'tasks', ['account_id', 'dedupe_key'])
        op.create_foreign_key(
            op.f('fk_tasks_source_rule_id_rules'),
            'tasks',
            'rules',
            ['source_rule_id'],
            ['id'],
            ondelete='SET NULL',
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _uses_sqlite_batch():
        with op.batch_alter_table('tasks', recreate='always') as batch_op:
            batch_op.drop_constraint(op.f('fk_tasks_source_rule_id_rules'), type_='foreignkey')
            batch_op.drop_constraint(op.f('uq_tasks_account_id'), type_='unique')
            batch_op.drop_column('escalated_at')
            batch_op.drop_column('escalation_level')
            batch_op.drop_column('dedupe_key')
            batch_op.drop_column('source_rule_id')
        with op.batch_alter_table('recommendations', recreate='always') as batch_op:
            batch_op.drop_constraint(op.f('fk_recommendations_source_rule_id_rules'), type_='foreignkey')
            batch_op.drop_constraint(op.f('uq_recommendations_account_id'), type_='unique')
            batch_op.drop_column('dedupe_key')
            batch_op.drop_column('source_rule_id')
        with op.batch_alter_table('alerts', recreate='always') as batch_op:
            batch_op.drop_constraint(op.f('fk_alerts_source_rule_id_rules'), type_='foreignkey')
            batch_op.drop_constraint(op.f('uq_alerts_account_id'), type_='unique')
            batch_op.drop_column('dedupe_key')
            batch_op.drop_column('source_rule_id')
    else:
        op.drop_constraint(op.f('fk_tasks_source_rule_id_rules'), 'tasks', type_='foreignkey')
        op.drop_constraint(op.f('uq_tasks_account_id'), 'tasks', type_='unique')
        op.drop_column('tasks', 'escalated_at')
        op.drop_column('tasks', 'escalation_level')
        op.drop_column('tasks', 'dedupe_key')
        op.drop_column('tasks', 'source_rule_id')
        op.drop_constraint(op.f('fk_recommendations_source_rule_id_rules'), 'recommendations', type_='foreignkey')
        op.drop_constraint(op.f('uq_recommendations_account_id'), 'recommendations', type_='unique')
        op.drop_column('recommendations', 'dedupe_key')
        op.drop_column('recommendations', 'source_rule_id')
        op.drop_constraint(op.f('fk_alerts_source_rule_id_rules'), 'alerts', type_='foreignkey')
        op.drop_constraint(op.f('uq_alerts_account_id'), 'alerts', type_='unique')
        op.drop_column('alerts', 'dedupe_key')
        op.drop_column('alerts', 'source_rule_id')
    op.drop_index('ix_rule_executions_account_rule_status', table_name='rule_executions')
    op.drop_index(op.f('ix_rule_executions_account_id'), table_name='rule_executions')
    op.drop_index('ix_rule_executions_account_entity_status', table_name='rule_executions')
    op.drop_table('rule_executions')
    op.drop_index('ix_threshold_configs_account_rule_status', table_name='threshold_configs')
    op.drop_index(op.f('ix_threshold_configs_account_id'), table_name='threshold_configs')
    op.drop_table('threshold_configs')
    op.drop_index('ix_rule_versions_rule_status', table_name='rule_versions')
    op.drop_table('rule_versions')
    op.drop_index('ix_rules_account_status', table_name='rules')
    op.drop_index('ix_rules_account_rule_type_status', table_name='rules')
    op.drop_index(op.f('ix_rules_account_id'), table_name='rules')
    op.drop_table('rules')
    # ### end Alembic commands ###
