"""business foundation

Revision ID: 2b380361744f
Revises: 20260418_0001
Create Date: 2026-04-18 12:28:27.743782

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '2b380361744f'
down_revision = '20260418_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=64), nullable=True),
    sa.Column('related_entity_id', sa.String(length=64), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_alerts_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('fk_alerts_assigned_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index('ix_alerts_account_code_status', 'alerts', ['account_id', 'code', 'status'], unique=False)
    op.create_index(op.f('ix_alerts_account_id'), 'alerts', ['account_id'], unique=False)
    op.create_index('ix_alerts_account_status_severity_last_detected', 'alerts', ['account_id', 'status', 'severity', 'last_detected_at'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_mask', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_bank_accounts_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_accounts')),
    sa.UniqueConstraint('account_id', 'provider', 'external_id', name=op.f('uq_bank_accounts_account_id'))
    )
    op.create_index(op.f('ix_bank_accounts_account_id'), 'bank_accounts', ['account_id'], unique=False)
    op.create_index('ix_bank_accounts_account_provider_status', 'bank_accounts', ['account_id', 'provider', 'status'], unique=False)
    op.create_index('ix_bank_accounts_account_status', 'bank_accounts', ['account_id', 'status'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_campaigns_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('account_id', 'source', 'external_id', name=op.f('uq_campaigns_account_id'))
    )
    op.create_index(op.f('ix_campaigns_account_id'), 'campaigns', ['account_id'], unique=False)
    op.create_index('ix_campaigns_account_source_status', 'campaigns', ['account_id', 'source', 'status'], unique=False)
    op.create_index('ix_campaigns_account_status', 'campaigns', ['account_id', 'status'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('customer_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('inn', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes_json', sa.JSON(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_customers_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('account_id', 'external_id', name=op.f('uq_customers_account_id'))
    )
    op.create_index(op.f('ix_customers_account_id'), 'customers', ['account_id'], unique=False)
    op.create_index('ix_customers_account_name', 'customers', ['account_id', 'name'], unique=False)
    op.create_index('ix_customers_account_status', 'customers', ['account_id', 'status'], unique=False)
    op.create_table('daily_kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kpi_date', sa.Date(), nullable=False),
    sa.Column('metric_code', sa.String(length=128), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_daily_kpis_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_kpis')),
    sa.UniqueConstraint('account_id', 'kpi_date', 'metric_code', name=op.f('uq_daily_kpis_account_id'))
    )
    op.create_index(op.f('ix_daily_kpis_account_id'), 'daily_kpis', ['account_id'], unique=False)
    op.create_index('ix_daily_kpis_account_kpi_date', 'daily_kpis', ['account_id', 'kpi_date'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('employee_code', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=128), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('hired_at', sa.Date(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_employees_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_employees_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('account_id', 'employee_code', name=op.f('uq_employees_account_id'))
    )
    op.create_index(op.f('ix_employees_account_id'), 'employees', ['account_id'], unique=False)
    op.create_index('ix_employees_account_status', 'employees', ['account_id', 'status'], unique=False)
    op.create_index('ix_employees_account_user_id', 'employees', ['account_id', 'user_id'], unique=False)
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_product_categories_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['product_categories.id'], name=op.f('fk_product_categories_parent_id_product_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_categories')),
    sa.UniqueConstraint('account_id', 'code', name=op.f('uq_product_categories_account_id'))
    )
    op.create_index(op.f('ix_product_categories_account_id'), 'product_categories', ['account_id'], unique=False)
    op.create_index('ix_product_categories_account_name', 'product_categories', ['account_id', 'name'], unique=False)
    op.create_index('ix_product_categories_account_parent_id', 'product_categories', ['account_id', 'parent_id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_warehouses_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    sa.UniqueConstraint('account_id', 'code', name=op.f('uq_warehouses_account_id'))
    )
    op.create_index(op.f('ix_warehouses_account_id'), 'warehouses', ['account_id'], unique=False)
    op.create_index('ix_warehouses_account_name', 'warehouses', ['account_id', 'name'], unique=False)
    op.create_index('ix_warehouses_account_status', 'warehouses', ['account_id', 'status'], unique=False)
    op.create_table('ad_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('leads_count', sa.Integer(), nullable=False),
    sa.Column('conversions_count', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_ad_metrics_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_ad_metrics_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_metrics')),
    sa.UniqueConstraint('account_id', 'campaign_id', 'metric_date', name=op.f('uq_ad_metrics_account_id'))
    )
    op.create_index(op.f('ix_ad_metrics_account_id'), 'ad_metrics', ['account_id'], unique=False)
    op.create_index('ix_ad_metrics_account_metric_date', 'ad_metrics', ['account_id', 'metric_date'], unique=False)
    op.create_table('balance_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_balance_snapshots_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], name=op.f('fk_balance_snapshots_bank_account_id_bank_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_balance_snapshots')),
    sa.UniqueConstraint('account_id', 'bank_account_id', 'snapshot_at', name=op.f('uq_balance_snapshots_account_id'))
    )
    op.create_index('ix_balance_snapshots_account_bank_snapshot_at', 'balance_snapshots', ['account_id', 'bank_account_id', 'snapshot_at'], unique=False)
    op.create_index(op.f('ix_balance_snapshots_account_id'), 'balance_snapshots', ['account_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_bank_transactions_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], name=op.f('fk_bank_transactions_bank_account_id_bank_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_transactions')),
    sa.UniqueConstraint('account_id', 'bank_account_id', 'provider_transaction_id', name=op.f('uq_bank_transactions_account_id'))
    )
    op.create_index('ix_bank_transactions_account_bank_posted_at', 'bank_transactions', ['account_id', 'bank_account_id', 'posted_at'], unique=False)
    op.create_index(op.f('ix_bank_transactions_account_id'), 'bank_transactions', ['account_id'], unique=False)
    op.create_index('ix_bank_transactions_account_posted_at', 'bank_transactions', ['account_id', 'posted_at'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_customer_id', sa.Integer(), nullable=True),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(length=64), nullable=True),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_expenses_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], name=op.f('fk_expenses_bank_account_id_bank_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_customer_id'], ['customers.id'], name=op.f('fk_expenses_supplier_customer_id_customers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index('ix_expenses_account_bank_account_id', 'expenses', ['account_id', 'bank_account_id'], unique=False)
    op.create_index('ix_expenses_account_category_expense_date', 'expenses', ['account_id', 'category', 'expense_date'], unique=False)
    op.create_index('ix_expenses_account_expense_date', 'expenses', ['account_id', 'expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_account_id'), 'expenses', ['account_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=64), nullable=False),
    sa.Column('first_response_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lost_reason', sa.Text(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_leads_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_leads_customer_id_customers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    sa.UniqueConstraint('account_id', 'source', 'external_id', name=op.f('uq_leads_account_id'))
    )
    op.create_index('ix_leads_account_customer_created_at', 'leads', ['account_id', 'customer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_leads_account_id'), 'leads', ['account_id'], unique=False)
    op.create_index('ix_leads_account_status_created_at', 'leads', ['account_id', 'status', 'created_at'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_type', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('list_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('min_stock_level', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('attributes_json', sa.JSON(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_products_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], name=op.f('fk_products_category_id_product_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('account_id', 'sku', name=op.f('uq_products_account_id'))
    )
    op.create_index('ix_products_account_category_status', 'products', ['account_id', 'category_id', 'status'], unique=False)
    op.create_index(op.f('ix_products_account_id'), 'products', ['account_id'], unique=False)
    op.create_index('ix_products_account_name', 'products', ['account_id', 'name'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_customer_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('purchase_number', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes_json', sa.JSON(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_purchases_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_customer_id'], ['customers.id'], name=op.f('fk_purchases_supplier_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_purchases_warehouse_id_warehouses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchases')),
    sa.UniqueConstraint('account_id', 'purchase_number', name=op.f('uq_purchases_account_id'))
    )
    op.create_index(op.f('ix_purchases_account_id'), 'purchases', ['account_id'], unique=False)
    op.create_index('ix_purchases_account_status_ordered_at', 'purchases', ['account_id', 'status', 'ordered_at'], unique=False)
    op.create_index('ix_purchases_account_supplier_id', 'purchases', ['account_id', 'supplier_customer_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=64), nullable=True),
    sa.Column('related_entity_id', sa.String(length=64), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_recommendations_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_recommendations_alert_id_alerts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index('ix_recommendations_account_alert_id', 'recommendations', ['account_id', 'alert_id'], unique=False)
    op.create_index(op.f('ix_recommendations_account_id'), 'recommendations', ['account_id'], unique=False)
    op.create_index('ix_recommendations_account_status_created_at', 'recommendations', ['account_id', 'status', 'created_at'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('assignee_employee_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('related_entity_type', sa.String(length=64), nullable=True),
    sa.Column('related_entity_id', sa.String(length=64), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_tasks_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assignee_employee_id'], ['employees.id'], name=op.f('fk_tasks_assignee_employee_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], name=op.f('fk_tasks_assignee_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_tasks_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index('ix_tasks_account_assignee_employee_status', 'tasks', ['account_id', 'assignee_employee_id', 'status'], unique=False)
    op.create_index('ix_tasks_account_assignee_user_status', 'tasks', ['account_id', 'assignee_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_account_id'), 'tasks', ['account_id'], unique=False)
    op.create_index('ix_tasks_account_status_due_at', 'tasks', ['account_id', 'status', 'due_at'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('deal_number', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cost_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_deals_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_deals_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_deals_lead_id_leads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_deals_owner_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deals')),
    sa.UniqueConstraint('account_id', 'deal_number', name=op.f('uq_deals_account_id'))
    )
    op.create_index('ix_deals_account_customer_id', 'deals', ['account_id', 'customer_id'], unique=False)
    op.create_index(op.f('ix_deals_account_id'), 'deals', ['account_id'], unique=False)
    op.create_index('ix_deals_account_lead_id', 'deals', ['account_id', 'lead_id'], unique=False)
    op.create_index('ix_deals_account_status_created_at', 'deals', ['account_id', 'status', 'created_at'], unique=False)
    op.create_table('lead_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_lead_events_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_lead_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_events_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_events'))
    )
    op.create_index(op.f('ix_lead_events_account_id'), 'lead_events', ['account_id'], unique=False)
    op.create_index('ix_lead_events_account_lead_event_at', 'lead_events', ['account_id', 'lead_id', 'event_at'], unique=False)
    op.create_index('ix_lead_events_account_type_event_at', 'lead_events', ['account_id', 'event_type', 'event_at'], unique=False)
    op.create_table('stock_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('quantity_reserved', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('min_quantity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reorder_quantity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('last_movement_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_stock_items_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_items_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_items_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_items')),
    sa.UniqueConstraint('account_id', 'warehouse_id', 'product_id', name=op.f('uq_stock_items_account_id'))
    )
    op.create_index(op.f('ix_stock_items_account_id'), 'stock_items', ['account_id'], unique=False)
    op.create_index('ix_stock_items_account_product_id', 'stock_items', ['account_id', 'product_id'], unique=False)
    op.create_index('ix_stock_items_account_warehouse_id', 'stock_items', ['account_id', 'warehouse_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.String(length=32), nullable=False),
    sa.Column('reference_type', sa.String(length=64), nullable=True),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('quantity_delta', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes_json', sa.JSON(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_stock_movements_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_movements_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], name=op.f('fk_stock_movements_purchase_id_purchases'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_movements_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements'))
    )
    op.create_index(op.f('ix_stock_movements_account_id'), 'stock_movements', ['account_id'], unique=False)
    op.create_index('ix_stock_movements_account_product_occurred_at', 'stock_movements', ['account_id', 'product_id', 'occurred_at'], unique=False)
    op.create_index('ix_stock_movements_account_purchase_id', 'stock_movements', ['account_id', 'purchase_id'], unique=False)
    op.create_index('ix_stock_movements_account_warehouse_occurred_at', 'stock_movements', ['account_id', 'warehouse_id', 'occurred_at'], unique=False)
    op.create_table('task_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_task_events_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_task_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_events_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_events'))
    )
    op.create_index(op.f('ix_task_events_account_id'), 'task_events', ['account_id'], unique=False)
    op.create_index('ix_task_events_account_task_event_at', 'task_events', ['account_id', 'task_id', 'event_at'], unique=False)
    op.create_index('ix_task_events_account_type_event_at', 'task_events', ['account_id', 'event_type', 'event_at'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('document_number', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('storage_kind', sa.String(length=32), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_documents_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_documents_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_documents_deal_id_deals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('account_id', 'document_type', 'document_number', name=op.f('uq_documents_account_id'))
    )
    op.create_index('ix_documents_account_customer_issued_at', 'documents', ['account_id', 'customer_id', 'issued_at'], unique=False)
    op.create_index('ix_documents_account_deal_id', 'documents', ['account_id', 'deal_id'], unique=False)
    op.create_index(op.f('ix_documents_account_id'), 'documents', ['account_id'], unique=False)
    op.create_index('ix_documents_account_issued_at', 'documents', ['account_id', 'issued_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_account_issued_at', table_name='documents')
    op.drop_index(op.f('ix_documents_account_id'), table_name='documents')
    op.drop_index('ix_documents_account_deal_id', table_name='documents')
    op.drop_index('ix_documents_account_customer_issued_at', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_task_events_account_type_event_at', table_name='task_events')
    op.drop_index('ix_task_events_account_task_event_at', table_name='task_events')
    op.drop_index(op.f('ix_task_events_account_id'), table_name='task_events')
    op.drop_table('task_events')
    op.drop_index('ix_stock_movements_account_warehouse_occurred_at', table_name='stock_movements')
    op.drop_index('ix_stock_movements_account_purchase_id', table_name='stock_movements')
    op.drop_index('ix_stock_movements_account_product_occurred_at', table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_account_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index('ix_stock_items_account_warehouse_id', table_name='stock_items')
    op.drop_index('ix_stock_items_account_product_id', table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_account_id'), table_name='stock_items')
    op.drop_table('stock_items')
    op.drop_index('ix_lead_events_account_type_event_at', table_name='lead_events')
    op.drop_index('ix_lead_events_account_lead_event_at', table_name='lead_events')
    op.drop_index(op.f('ix_lead_events_account_id'), table_name='lead_events')
    op.drop_table('lead_events')
    op.drop_index('ix_deals_account_status_created_at', table_name='deals')
    op.drop_index('ix_deals_account_lead_id', table_name='deals')
    op.drop_index(op.f('ix_deals_account_id'), table_name='deals')
    op.drop_index('ix_deals_account_customer_id', table_name='deals')
    op.drop_table('deals')
    op.drop_index('ix_tasks_account_status_due_at', table_name='tasks')
    op.drop_index(op.f('ix_tasks_account_id'), table_name='tasks')
    op.drop_index('ix_tasks_account_assignee_user_status', table_name='tasks')
    op.drop_index('ix_tasks_account_assignee_employee_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_recommendations_account_status_created_at', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_account_id'), table_name='recommendations')
    op.drop_index('ix_recommendations_account_alert_id', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_purchases_account_supplier_id', table_name='purchases')
    op.drop_index('ix_purchases_account_status_ordered_at', table_name='purchases')
    op.drop_index(op.f('ix_purchases_account_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index('ix_products_account_name', table_name='products')
    op.drop_index(op.f('ix_products_account_id'), table_name='products')
    op.drop_index('ix_products_account_category_status', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_leads_account_status_created_at', table_name='leads')
    op.drop_index(op.f('ix_leads_account_id'), table_name='leads')
    op.drop_index('ix_leads_account_customer_created_at', table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_expenses_account_id'), table_name='expenses')
    op.drop_index('ix_expenses_account_expense_date', table_name='expenses')
    op.drop_index('ix_expenses_account_category_expense_date', table_name='expenses')
    op.drop_index('ix_expenses_account_bank_account_id', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_bank_transactions_account_posted_at', table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_account_id'), table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_account_bank_posted_at', table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_balance_snapshots_account_id'), table_name='balance_snapshots')
    op.drop_index('ix_balance_snapshots_account_bank_snapshot_at', table_name='balance_snapshots')
    op.drop_table('balance_snapshots')
    op.drop_index('ix_ad_metrics_account_metric_date', table_name='ad_metrics')
    op.drop_index(op.f('ix_ad_metrics_account_id'), table_name='ad_metrics')
    op.drop_table('ad_metrics')
    op.drop_index('ix_warehouses_account_status', table_name='warehouses')
    op.drop_index('ix_warehouses_account_name', table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_account_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index('ix_product_categories_account_parent_id', table_name='product_categories')
    op.drop_index('ix_product_categories_account_name', table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_account_id'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index('ix_employees_account_user_id', table_name='employees')
    op.drop_index('ix_employees_account_status', table_name='employees')
    op.drop_index(op.f('ix_employees_account_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_daily_kpis_account_kpi_date', table_name='daily_kpis')
    op.drop_index(op.f('ix_daily_kpis_account_id'), table_name='daily_kpis')
    op.drop_table('daily_kpis')
    op.drop_index('ix_customers_account_status', table_name='customers')
    op.drop_index('ix_customers_account_name', table_name='customers')
    op.drop_index(op.f('ix_customers_account_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_campaigns_account_status', table_name='campaigns')
    op.drop_index('ix_campaigns_account_source_status', table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_account_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_bank_accounts_account_status', table_name='bank_accounts')
    op.drop_index('ix_bank_accounts_account_provider_status', table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_account_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index('ix_alerts_account_status_severity_last_detected', table_name='alerts')
    op.drop_index(op.f('ix_alerts_account_id'), table_name='alerts')
    op.drop_index('ix_alerts_account_code_status', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
