"""integration foundation

Revision ID: 7763ddc6df3e
Revises: 2b380361744f
Create Date: 2026-04-18 12:40:14.619327

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7763ddc6df3e'
down_revision = '2b380361744f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_kind', sa.String(length=32), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('external_ref', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('connection_mode', sa.String(length=32), nullable=False),
    sa.Column('sync_mode', sa.String(length=32), nullable=False),
    sa.Column('webhook_url', sa.String(length=512), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_webhook_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_integrations_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations')),
    sa.UniqueConstraint('account_id', 'provider_kind', 'provider_name', 'external_ref', name=op.f('uq_integrations_account_id'))
    )
    op.create_index(op.f('ix_integrations_account_id'), 'integrations', ['account_id'], unique=False)
    op.create_index('ix_integrations_account_provider_kind_status', 'integrations', ['account_id', 'provider_kind', 'status'], unique=False)
    op.create_index('ix_integrations_account_provider_name', 'integrations', ['account_id', 'provider_name'], unique=False)
    op.create_index('ix_integrations_account_status', 'integrations', ['account_id', 'status'], unique=False)
    op.create_table('integration_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('credential_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('secret_ciphertext', sa.Text(), nullable=False),
    sa.Column('secret_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('last_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_integration_credentials_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_integration_credentials_integration_id_integrations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_credentials')),
    sa.UniqueConstraint('account_id', 'integration_id', 'credential_type', 'version', name=op.f('uq_integration_credentials_account_id'))
    )
    op.create_index(op.f('ix_integration_credentials_account_id'), 'integration_credentials', ['account_id'], unique=False)
    op.create_index('ix_integration_credentials_account_integration_status', 'integration_credentials', ['account_id', 'integration_id', 'status'], unique=False)
    op.create_index('ix_integration_credentials_account_type_status', 'integration_credentials', ['account_id', 'credential_type', 'status'], unique=False)
    op.create_table('provider_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('token_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('access_token_ciphertext', sa.Text(), nullable=True),
    sa.Column('refresh_token_ciphertext', sa.Text(), nullable=True),
    sa.Column('scopes_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_provider_tokens_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_provider_tokens_integration_id_integrations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_tokens')),
    sa.UniqueConstraint('account_id', 'integration_id', 'token_type', name=op.f('uq_provider_tokens_account_id'))
    )
    op.create_index('ix_provider_tokens_account_expires_at', 'provider_tokens', ['account_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_provider_tokens_account_id'), 'provider_tokens', ['account_id'], unique=False)
    op.create_index('ix_provider_tokens_account_integration_status', 'provider_tokens', ['account_id', 'integration_id', 'status'], unique=False)
    op.create_table('sync_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('provider_kind', sa.String(length=32), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('trigger_mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scope_json', sa.JSON(), nullable=False),
    sa.Column('cursor_json', sa.JSON(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_sync_jobs_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_sync_jobs_integration_id_integrations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_jobs')),
    sa.UniqueConstraint('account_id', 'idempotency_key', name=op.f('uq_sync_jobs_account_id'))
    )
    op.create_index(op.f('ix_sync_jobs_account_id'), 'sync_jobs', ['account_id'], unique=False)
    op.create_index('ix_sync_jobs_account_integration_status', 'sync_jobs', ['account_id', 'integration_id', 'status'], unique=False)
    op.create_index('ix_sync_jobs_account_provider_kind_job_type', 'sync_jobs', ['account_id', 'provider_kind', 'job_type'], unique=False)
    op.create_index('ix_sync_jobs_account_status_scheduled_at', 'sync_jobs', ['account_id', 'status', 'scheduled_at'], unique=False)
    op.create_table('integration_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('sync_job_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider_kind', sa.String(length=32), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_integration_logs_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_integration_logs_integration_id_integrations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_job_id'], ['sync_jobs.id'], name=op.f('fk_integration_logs_sync_job_id_sync_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_logs'))
    )
    op.create_index(op.f('ix_integration_logs_account_id'), 'integration_logs', ['account_id'], unique=False)
    op.create_index('ix_integration_logs_account_integration_created_at', 'integration_logs', ['account_id', 'integration_id', 'created_at'], unique=False)
    op.create_index('ix_integration_logs_account_level_created_at', 'integration_logs', ['account_id', 'level', 'created_at'], unique=False)
    op.create_index('ix_integration_logs_account_sync_job_created_at', 'integration_logs', ['account_id', 'sync_job_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_integration_logs_account_sync_job_created_at', table_name='integration_logs')
    op.drop_index('ix_integration_logs_account_level_created_at', table_name='integration_logs')
    op.drop_index('ix_integration_logs_account_integration_created_at', table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_account_id'), table_name='integration_logs')
    op.drop_table('integration_logs')
    op.drop_index('ix_sync_jobs_account_status_scheduled_at', table_name='sync_jobs')
    op.drop_index('ix_sync_jobs_account_provider_kind_job_type', table_name='sync_jobs')
    op.drop_index('ix_sync_jobs_account_integration_status', table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_account_id'), table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_index('ix_provider_tokens_account_integration_status', table_name='provider_tokens')
    op.drop_index(op.f('ix_provider_tokens_account_id'), table_name='provider_tokens')
    op.drop_index('ix_provider_tokens_account_expires_at', table_name='provider_tokens')
    op.drop_table('provider_tokens')
    op.drop_index('ix_integration_credentials_account_type_status', table_name='integration_credentials')
    op.drop_index('ix_integration_credentials_account_integration_status', table_name='integration_credentials')
    op.drop_index(op.f('ix_integration_credentials_account_id'), table_name='integration_credentials')
    op.drop_table('integration_credentials')
    op.drop_index('ix_integrations_account_status', table_name='integrations')
    op.drop_index('ix_integrations_account_provider_name', table_name='integrations')
    op.drop_index('ix_integrations_account_provider_kind_status', table_name='integrations')
    op.drop_index(op.f('ix_integrations_account_id'), table_name='integrations')
    op.drop_table('integrations')
    # ### end Alembic commands ###
